#! /usr/bin/env bash

#cp ~/.ssh/isit320-Fall-2019 system-environment/.
cp ~/.ssh/midterm-key system-environment/.

docker-compose up $1
#rm system-environment/isit320-Fall-2019
rm system-environment/midterm-key