#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

NORMAL_PORT=true

if [[ -z $1  ]]; then
    echo "======================================================"
    echo -e ${LIGHT_RED}"Aborting." ${YELLOW}"You must pass in a version number."$NC       
    echo "Example:"
    echo -e $LIGHT_GREEN  "push_images_to_docker_hub '01'"$NC
    echo "======================================================"
    exit
fi

docker network create -d bridge lucasnet
docker pull exxxius/gitignore_main:version$1
docker pull exxxius/gitignore_system-environment:version$1
docker pull exxxius/gitignore_route-tester:version$1

docker container run --name main -d -p 30025:30025 --network lucasnet exxxius/gitignore_main:version$1
docker container run --name system-environment -d -p 30028:30028 --network lucasnet exxxius/gitignore_system-environment:version$1
docker container run --name route-tester -d -p 30029:30029 --network lucasnet exxxius/gitignore_route-tester:version$1

