#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

NORMAL_PORT=true

if [[ -z $1  ]]; then
    echo "======================================================"
    echo -e ${LIGHT_RED}"Aborting." ${YELLOW}"You must pass in a version number."$NC       
    echo "Example:"
    echo -e $LIGHT_GREEN  "push_images_to_docker_hub '01'"$NC
    echo "======================================================"
    exit
fi

docker tag switchrepos_main:latest exxxius/gitignore_main:version$1
docker tag switchrepos_system-environment:latest exxxius/gitignore_system-environment:version$1
docker tag switchrepos_route-tester:latest exxxius/gitignore_route-tester:version$1
docker push exxxius/gitignore_main:version$1
docker push exxxius/gitignore_system-environment:version$1
docker push exxxius/gitignore_route-tester:version$1
